# FROM node:12-alpine
# RUN apk add --no-cache \
#     autoconf \
#     automake \
#     autoconf \
#     libtool \
#     bash \
#     g++ \
#     libc6-compat \
#     libjpeg-turbo-dev \
#     libpng-dev \
#     make \
#     nasm
# WORKDIR /app
# COPY package.json /app
# RUN npm install
# COPY . /app
# RUN npm run build
# EXPOSE 3000
# CMD [ "npm", "run", "start" ]

FROM nginx:1.19
EXPOSE 80
COPY . /app
COPY app/build /usr/share/nginx/html
RUN ls /usr/share/nginx/html
COPY ./infra/nginx/default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]