apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ctbc-frontend-clone-and-build-run-
spec:
  serviceAccountName: ctbc-frontend-deployer
  pipelineRef:
    name: ctbc-frontend-clone-and-build-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi