apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctbc-frontend-deployer
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - patch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctbc-frontend-deployer
subjects:
  - kind: ServiceAccount
    name: ctbc-frontend-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctbc-frontend-deployer
