// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

// Auth
export const AUTH_INIT = "AUTH_INIT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";

// Login
export const LOGIN_STATUS_INIT = "LOGIN_STATUS_INIT";
export const LOGIN_STATUS_PENDING = "LOGIN_STATUS_PENDING";
export const LOGIN_STATUS_SUCCESS = "LOGIN_STATUS_SUCCESS";
export const LOGIN_STATUS_ERROR = "LOGIN_STATUS_ERROR";

// ADFS Login
export const ADFS_LOGIN_STATUS_SEND_TO_AUTHPROXY_INIT = "ADFS_LOGIN_STATUS_SEND_TO_AUTHPROXY_INIT";
export const ADFS_LOGIN_STATUS_SEND_TO_AUTHPROXY_SUCCESS = "ADFS_LOGIN_STATUS_SEND_TO_AUTHPROXY_SUCCESS";
export const ADFS_LOGIN_STATUS_SEND_AUTHPROXY_FAIL = "ADFS_LOGIN_STATUS_SEND_AUTHPROXY_FAIL";
export const ADFS_LOGIN_STATUS_RESPONSE_TO_CTBC_STATUS_INIT = "ADFS_LOGIN_STATUS_RESPONSE_TO_CTBC_STATUS_INIT";
export const ADFS_LOGIN_STATUS_RESPONSE_TO_CTBC_SUCCESS = "ADFS_LOGIN_STATUS_RESPONSE_TO_CTBC_SUCCESS";
export const ADFS_LOGIN_STATUS_RESPONSE_TO_CTBC_FAIL = "ADFS_LOGIN_STATUS_RESPONSE_TO_CTBC_FAIL";

// DataSource
export const DATA_SOURCE_DEFINE = "DATA_SOURCE_DEFINE";
export const DATA_SOURCE_REGION_INIT = "DATA_SOURCE_INIT";
export const DATA_SOURCE_REGION_SUCCESS = "DATA_SOURCE_REGION_SUCCESS";

// Dashboard
export const DASHBOARD_STATUS_INIT = "DASHBOARD_STATUS_INIT";
export const DASHBOARD_STATUS_SUCCESS = "DASHBOARD_STATUS_SUCCESS";
export const DASHBOARD_STATUS_ERROR = "DASHBOARD_STATUS_ERROR";

// Topic List
export const TOPIC_LIST_INIT = "TOPIC_LIST_INIT";
export const TOPIC_LIST_SUCCESS = "TOPIC_LIST_SUCCESS";
export const TOPIC_LIST_ERROR = "TOPIC_LIST_ERROR";

// Pane (USC)
export const PANE_STATUS_INIT = "PANE_STATUS_INIT";
export const PANE_STATUS_SUCCESS = "PANE_STATUS_SUCCESS";
export const PANE_STATUS_ERROR = "PANE_STATUS_ERROR";
export const PANE_COUNTER_STATUS_SUCCESS = "PANE_COUNTER_STATUS_SUCCESS";
export const PANE_COUNTER_STATUS_ERROR = "PANE_COUNTER_STATUS_ERROR";

// Partner Detail
export const PARTNER_DETAIL_STATUS_INIT = "PARTNER_DETAIL_STATUS_INIT";
export const PARTNER_DETAIL_STATUS_SUCCESS = "PARTNER_DETAIL_STATUS_SUCCESS";
export const PARTNER_DETAIL_STATUS_ERROR = "PARTNER_DETAIL_STATUS_ERROR";
export const PARTNER_DETAIL_HAS_WRONG_SEARCHID = "PARTNER_DETAIL_HAS_WRONG_SEARCHID";

// Customer list (USC)
export const CUSTOMER_STATUS_INIT = "CUSTOMER_STATUS_INIT";
export const CUSTOMER_TM_STATUS_SUCCESS = "CUSTOMER_TM_STATUS_SUCCESS";
export const CUSTOMER_TM_STATUS_ERROR = "CUSTOMER_TM_STATUS_ERROR";
export const CUSTOMER_MSP_STATUS_SUCCESS = "CUSTOMER_MSP_STATUS_SUCCESS";
export const CUSTOMER_MSP_STATUS_ERROR = "CUSTOMER_MSP_STATUS_ERROR";